services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  mztx\pet\Command\:
    resource: '../src/Command/*'
    tags:
      - "pet.cli.command"

  mztx\pet\Command\CacheClearCommand:
    tags:
      - "pet.cli.command"
    arguments:
      $configDir: '%env(PET_CONFIG_DIR)%'

  mztx\pet\Application:
    public: true
    arguments:
      $name: "PET - Personal Timetracker"
      $version: "__DEV__"
